name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      run: sudo apt update && sudo apt install openjdk-17-jdk gradle

    - name: Test with Gradle Wrapper
      run: gradle test
